name: Docker Lint and Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run hadolint
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      # Prepare & run pylint
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint # Ensures lint job passes before this job runs

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Build image
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target addon-folder
