name: Docker Lint and Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run hadolint
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v2
        with:
          dockerfile: Dockerfile

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint # Ensures lint job passes before this job runs

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for better compatibility
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build image
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
